# Unique identifier: Attempt 002
workflows:
  ios:
    name: iOS Workflow
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods
          pod install
      - name: Build the app
        script: |
          xcodebuild -workspace ios/FloorOrganizer.xcworkspace -scheme FloorOrganizer -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/FloorOrganizer.xcarchive
    artifacts:
      - build/ios/**/*.app
    distribution:
      method: app-store
